db:
  connection_string: pgsql://postgres@localhost/endpoint
money:
  yandex:
    wallet:
      shared_key:
      sign_arguments:
        - notification_type
        - operation_id
        - amount
        - currency
        - datetime
        - sender
        - codepro
        - notification_secret
        - label